#!/usr/bin/zsh --

APP_NAME=$(basename $0)

if [ "$#" -eq 0 ];
then
   echo "Usage: $APP_NAME <project-name> [package-name]"
   exit 1
fi

PROJECT_NAME=$1
PACKAGE_NAME=com.mycompany.app

if [ "$#" -eq 2 ];
then
   PACKAGE_NAME=$2
fi

CMD="mvn archetype:generate"
PROJECT="-DgroupId=$PACKAGE_NAME -DartifactId=$PROJECT_NAME"
ARCHETYPES="-DarchetypeArtifactId=maven-archetype-quickstart"
OPTIONS="-DarchetypeVersion=1.5 -DinteractiveMode=false"

eval "$CMD $PROJECT $ARCHETYPES $OPTIONS"


